### ISSUE TITLE
Downloadable JS has gone away

### ISSUE THREAD

**Issue by entozoon** [thomascgray/fantasy-content-generator#4]
The instructions [reference](https://github.com/thomascgray/fantasy-content-generator#browserdirect-script-include) a direct download of [fantasy_content_generator.js](https://raw.githubusercontent.com/thomascgray/fantasy-content-generator/master/fantasy_content_generator.js) but it's gone missing.
NPM package works fine, but for a cheeky quick download it's a no show.

Love the app though, convincing names!

**Comment by Kaikas** [comment]
Same here. Wanted to do a quick test, but the .js file is empty.

**Comment by tomcgray** [comment]
Hey, thanks so much for raising the issue.

The 1 sentence tl;dr is:
Dependency hell causing silent bugs.

The slightly longer version is: 
Sometime in-between the "browser build" functionality being written and now, Browserify stopped working either for me/for Windows 10/some other specific scenario of which my development machine is included in the venn diagram of. However, it stopped working _silently_, so the file was still present but completely empty.

Solution is:
I've completely removed the Browserify functionality and replaced it with Parcel which I much prefer anyway. 

[fantasy_content_generator.js}(https://raw.githubusercontent.com/thomascgray/fantasy-content-generator/master/fantasy_content_generator.js) should be there again in full, ready to be included in a browser script tag and used.

Thanks again!
